using System;
using System.Threading.Tasks;
using LowBackPain.PatientImages;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Volo.Abp;
using Volo.Abp.AspNetCore.Mvc;
using Volo.Abp.Content;

namespace LowBackPain.Controllers;

/// <summary>
/// Patient Image Controller
/// 患者图像控制器 - Only handles multipart/form-data upload
/// Other endpoints are auto-generated by ABP from IPatientImageAppService
/// </summary>
[Area("app")]
[Route("api/app/patient-image")]
[ApiExplorerSettings(IgnoreApi = false)]
public class PatientImageController : AbpControllerBase
{
    private readonly IPatientImageAppService _patientImageAppService;

    public PatientImageController(IPatientImageAppService patientImageAppService)
    {
        _patientImageAppService = patientImageAppService;
    }

    /// <summary>
    /// Upload an image for a patient
    /// 上传患者图像
    /// </summary>
    [HttpPost("upload")]
    [Consumes("multipart/form-data")]
    public async Task<PatientImageDto> UploadAsync(
        [FromForm] Guid patientId,
        [FromForm] string imageType,
        [FromForm] string description,
        IFormFile file)
    {
        if (file == null || file.Length == 0)
        {
            throw new BusinessException("FILE_EMPTY");
        }

        var remoteStreamContent = new RemoteStreamContent(
            file.OpenReadStream(),
            file.FileName,
            file.ContentType,
            file.Length);

        return await _patientImageAppService.UploadAsync(
            patientId,
            remoteStreamContent,
            imageType,
            description);
    }
}
